### ISSUE TITLE
Fmovies dead

### ISSUE THREAD

**Issue by ligix** [Shakil-Shahadat/awesome-piracy#101]
Fmovies appear to have died

> As things stand today, Fmovies appears to be dead. The site first showed signs of distress around June 22/23 when it stopped updating with new content. Around noon on July 16, everything went black, and that was that.

https://torrentfreak.com/what-killed-fmovies-death-by-a-1000-cuts-one-killer-blow-or-possibly-both-240719/

**Comment by ligix** [comment]
>Current status	Defunct

https://en.wikipedia.org/wiki/FMovies

**Comment by Shakil-Shahadat** [comment]
Removed Fmovies. Should I keep [FMoviesPlus.bundle](https://github.com/coder-alpha/FMoviesPlus.bundle)?

**Comment by ligix** [comment]
I'd remove it
