### ISSUE TITLE
Websites that don't work

### ISSUE THREAD

**Issue by technub1** [Shakil-Shahadat/awesome-piracy#102]
It appears the following websites aren't loading compared to the others

https://zooqle.com/ - Domain ownership looks to have changed
https://www.ettv.tv/
https://games4theworld.org/
https://www.skytorrents.lol/ - Site doesn't look right
https://otorrents.com/ - Domain was given up or taken

**Comment by Shakil-Shahadat** [comment]
https://games4theworld.org/ seems fine.

**Comment by Shakil-Shahadat** [comment]
The rest of them are removed.
