### ISSUE TITLE
Public Trackers that Don't Work

### ISSUE THREAD

**Issue by technub1** [Shakil-Shahadat/awesome-piracy#103]
Isohunt2 - Doesn't load or seem to "exist" anymore
The Proxy Bay - Don't know if this comes and goes, but it's not loading for me right now
MagnetDL - Seems to be a CDN Host down error 522, not sure if this is temporary or how long it's been going on for. But i know this is a reputable site
Pirateiro - Doesn't appear to be loading
TorrentKing - Redirects to "amomama.com" and is unrelated now
Torrent9 - Seems to redirect to maddatings.com or astrowow.com now
Torrenty.org - 
WorldWide Torrents - Doesn't load or seem to "exist" anymore

**Comment by Shakil-Shahadat** [comment]
Pirateiro and Torrenty.org are okay. Will wait a bit for MagnetDL. The rest of them are removed.
