### ISSUE TITLE
Movidy.co is no longer functional (hasn’t been since 2020)

### ISSUE THREAD

**Issue by MrFrio** [Shakil-Shahadat/awesome-piracy#24]
Tested yesterday and today in both safari on an iPhone and Google Chrome on windows. Won’t load up on any device

**Comment by MrFrio** [comment]
Using wayback, the website shows a warning saying that xDede will now be called Movidy and the domain will no longer remain operative on January 10 of 2020

**Comment by Shakil-Shahadat** [comment]
Thanks. If you have time, please check other links. There are a ton of dead links out there.
