### ISSUE TITLE
[Request] some sites and apps...

### ISSUE THREAD

**Issue by Heus-Sueh** [Shakil-Shahadat/awesome-piracy#29]
android app to watch animes and read mangas: 
https://github.com/jmir1/aniyomi

for the repacks category: 
https://dodi-repacks.site/
https://scooter-repacks.site/
https://repack.info/
https://masquerade.site/

windows piracy:
(Microsoft Activation Scripts) https://massgrave.dev/index.html

**Comment by Shakil-Shahadat** [comment]
Please allow me some time to add these links as I am going through some personal issues right now. Thanks.

**Comment by Heus-Sueh** [comment]
no problem man, take your time :)
