### ISSUE TITLE
Add 2 new Course websites

### ISSUE THREAD

**Issue by BoscoDomingo** [Shakil-Shahadat/awesome-piracy#3]
[TutsNode](https://tutsnode.net/) and [FreeCoursesOnline](https://www.freecoursesonline.me/?1)

**Comment by Shakil-Shahadat** [comment]
Sorry, I haven't seen your issue cause I didn't get any notification.

Anyway, both links are added to [Courses and Tutorials](https://github.com/Shakil-Shahadat/awesome-piracy#courses-and-tutorials).
