### ISSUE TITLE
[request] A ddl tool

### ISSUE THREAD

**Issue by FrenchGithubUser** [Shakil-Shahadat/awesome-piracy#34]
Hi, I am currently developping a ddl tool for various files and websites. Its goald is to cover most fields. It is already available here : https://github.com/FrenchGithubUser/Hatt

Would it be possible to add it to the list ?

**Comment by Shakil-Shahadat** [comment]
Sure. This looks nice. Can you please send a pr? I don't have access to pc these days.

**Comment by FrenchGithubUser** [comment]
Done !

**Comment by Shakil-Shahadat** [comment]
Thanks. Done on my part too.
