### ISSUE TITLE
polish trackers

### ISSUE THREAD

**Issue by kompowiec** [Shakil-Shahadat/awesome-piracy#38]
### Public
http://bitnova.info/
http://elitetorrent.pl/
http://devil-torrents.pl/
http://ex-torrenty.org/
http://polskie-torrenty.net.pl/
http://vtorrent.pl/
http://helltorrents.com/
http://xtorrenty.org/
http://torrentcity.pl/
http://darmowe-torenty.pl/
http://electro-torrent.pl/
https://feniks-site.com.pl/
http://dark-torrents.pl/
https://best-torrents.org/
### Private
http://plsrc.cz/
https://pte.nu/
http://rstorrent.org.pl/
https://torrentleech.pl/
https://cinemamovies.pl/
http://central-torrent.eu/
https://exitorrent.org/
http://www.dvdseed.eu/
http://bigbbs.eu/

**Comment by Shakil-Shahadat** [comment]
Can you send a PR?

**Comment by Shakil-Shahadat** [comment]
All live links added here https://github.com/Shakil-Shahadat/awesome-piracy?tab=readme-ov-file#poland
