### ISSUE TITLE
ReBack navigation panel to inform how to use ctrl + f

### ISSUE THREAD

**Issue by KonoromiHimaries** [Shakil-Shahadat/awesome-piracy#50]
```
https://github.com/Igglybuff/awesome-piracy#how-to-use-this-list
```

**Comment by abcasada** [comment]
@KonoromiHimaries, can you please clarify what you mean by "ReBack"?

**Comment by Shakil-Shahadat** [comment]
Check the given link.

**Comment by abcasada** [comment]
I have looked at that section. However, I guess I'm unfamiliar with the term reback. Can you clarify the meaning of reback in this context? I'd like to help resolve this issue if possible.
