### ISSUE TITLE
GFXtra downloads are paywalled

### ISSUE THREAD

**Issue by killerqueer** [Shakil-Shahadat/awesome-piracy#56]
Every download link I have tried on the website has not allowed me to download the files without paying a monthly fee for the file-sharing website. I've attached an example of the download page after clicking the "free download" button below.

![Screenshot 2023-07-07 at 04-36-24 Download Resist Mono rar](https://github.com/Shakil-Shahadat/awesome-piracy/assets/75750259/0991448a-d0a3-4cef-bfcf-7b34c8e84939)

**Comment by Shakil-Shahadat** [comment]
Removed. Thanks.
