### ISSUE TITLE
Torrent.csv is down

### ISSUE THREAD

**Issue by Gavinok** [Shakil-Shahadat/awesome-piracy#72]
Torrent.csv has been taken down as well as torrent-csv.ml.

**Comment by Shakil-Shahadat** [comment]
How do you know that torrent-csv.ml has been taken down? There is no word on google, torrent freak or in r/piracy. Let's wait a bit and will remove it if needed.

**Comment by abcasada** [comment]
Has anyone seen any word about Torrent.csv? It seems to be permanently gone.

https://www.reddit.com/r/Piracy/comments/18ek5ac/is_torrentscsv_dead/

I recommend removing it at this point, if so.
