### ISSUE TITLE
Torrent Galaxy down or moved

### ISSUE THREAD

**Issue by abcasada** [Shakil-Shahadat/awesome-piracy#74]
Your URL listed in readme.md for TorrentGalaxy (https://torrentgalaxy.org) redirects to http://ww01.torrentgalaxy.org/listing, which has a mostly empty HTML page with title "Torrentgalaxy.org is for sale!"

A quick Google search for "torrent galaxy" leads to this URL: https://torrentgalaxy-official.site/

I'm not familiar with this site at all but this URL would appear to be its new home.

**Comment by Shakil-Shahadat** [comment]
Updated the link.

https://torrentgalaxy-official.site/ is a new site, better not trust it.
