### ISSUE TITLE
Google Unlocked abandoned, not working

### ISSUE THREAD

**Issue by kubagp1** [Shakil-Shahadat/awesome-piracy#89]
[https://github.com/Ibit-to/google-unlocked/issues/40](https://github.com/Ibit-to/google-unlocked/issues/40)

**Comment by Shakil-Shahadat** [comment]
The link you shared says, browser extensions are dead but the userscript version still works. Thus, removed it from 'Browser Extensions' and added it in the 'Userscript' section. Thanks.
