### ISSUE TITLE
IDM trial reset tool broken or not updated

### ISSUE THREAD

**Issue by RaduAnPlay** [Shakil-Shahadat/awesome-piracy#91]
The idm trial reset tool doesn't work and it's unchanged from 2016 being the last update in the github repo

**Comment by Shakil-Shahadat** [comment]
Try this https://github.com/Qynklee/IDM-Reset-Tool and this https://github.com/WindowsAddict/IDM-Activation-Script. Let me know if any of them work.

**Comment by Shakil-Shahadat** [comment]
Also, the crack by Ali.Dbg has the trial reset function if you know where to find it.

**Comment by RaduAnPlay** [comment]
tries both and are all deprecated windows addict is now public  and qynklee only gives me a contact admin error

**Comment by Shakil-Shahadat** [comment]
> Also, the crack by Ali.Dbg has the trial reset function if you know where to find it.

Did you try that?

**Comment by RaduAnPlay** [comment]
yes all the reccomended

**Comment by Shakil-Shahadat** [comment]
If this can be be reported to Ali.Dbg, I think he will be able to solve this, but I don't know how to reach him. May be you can make a post about 'IDM Trial Reset' in general in r/piracy, someone might be able to come out with a solution.

**Comment by RaduAnPlay** [comment]
thx

**Comment by Shakil-Shahadat** [comment]
Let me know if anything works or if you have got any solution. I'll add that to the repo.
