### ISSUE TITLE
Vimm's Lair DMCA

### ISSUE THREAD

**Issue by commandcontrolQ** [Shakil-Shahadat/awesome-piracy#93]
Recently, Vimm's Lair received a **DMCA takedown notice** from Nintendo of America, taking down all 'Mario' games in the Vault.

While the games still exist in the server, the download button has been removed and replaced with a disclaimer.

In order to restore the download functionality, there is a script that you can use that automatically replaces the disclaimer with a download button.

## This script has been tested and works on both Tampermonkey and Greasemonkey.
Unzip [this file](https://github.com/user-attachments/files/15526066/vvbypass.user.zip) and copy its contents to the Tampermonkey/Greasemonkey editor.

**Comment by Shakil-Shahadat** [comment]
Can you upload this to https://greasyfork.org/en?

**Comment by commandcontrolQ** [comment]
This script as of June 2024 does not work anymore. The trick used to download the games now serves no purpose as:
1. The download server changed (from download3.vimm.net to download2.vimm.net)
2. Every game affected by the DMCA takedowns was removed from the download servers.
As such, I do not plan on uploading this to Greasy Fork.
