### ISSUE TITLE
There was a gaming site called `nosteam` or something like that

### ISSUE THREAD

**Issue by Obegg** [Shakil-Shahadat/awesome-piracy#94]
I remember back in the day there was a gaming site called `nosteam` or something like that.
I can't remember the URL, are you familiar with that website? if so - why it's not added to the [list](https://github.com/Shakil-Shahadat/awesome-piracy?tab=readme-ov-file#gaming)?

**Comment by Shakil-Shahadat** [comment]
This is not a piracy support repository or anything like that. And it is not added here because you forgot the name and didn't add it.

This is not even my list, I'm just maintaining it. Literally, the first line of the repo clarifies that.
